apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name}}
  labels:
    {{ .Values.deployment.labelsKey }}: {{ .Values.deployment.labelsValue }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ .Values.pod.labelsKey }} : {{ .Values.pod.labelsValue }}
  template:
    metadata:
      labels:
        {{ .Values.pod.labelsKey }} : {{ .Values.pod.labelsValue }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.container.port }}