# CICD using GitHub Actions

name: CI

# Exclude the workfow to run on changes to the helm chart

on:
  push:
    branches:
      - ci-cd
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'helm/**'
jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        
        - name: Set up Go 1.22
          uses: actions/setup-go@v2
          with:
            go-version: 1.22
          
        - name: Build
          run: go build -o go-web-app .

        - name: Test
          run: go test ./...
    
    code-quality:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Run golangci-lint
          uses: golangci/golangci-lint-action@v6
          with:
            version: v1.56.2
      
    docker-build-and-push:
      runs-on: 
        ubuntu-latest
      
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        
        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
          
        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/go-web-app:{{ github.run_id }}
    
    update-newtag-in-helm-chart:
      runs-on: ubuntu-latest

      needs: docker-build-and-push

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        
        - name: Update tag in Helm chart
          run: |
            sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' helm/go-web-app-chart/values.yaml

        - name: Commit and push changes
          run: |
            git config --global user.email "narsss1234@gmail.com"
            git config --global user.name "Satya"
            git add helm/go-web-app-chart/values.yaml
            git commit -m "Update tag in Helm chart"
            git push